include ../platform-settings

CFLAGS:=$(CFLAGS) -I../jabberd
dialback_OBJECTS=dialback.o dialback_in.o dialback_out.o dllinit.o

all: dialback

dialback: $(dialback_OBJECTS)
	dllwrap --def ../cygwin/dialback.def --driver-name $(CC) -o dialback.dll $(dialback_OBJECTS) ../jabberd/jabberd.a $(LDFLAGS)

static: $(dialback_OBJECTS)

single: $(dialback_OBJECTS)

clean:
	rm -f $(dialback_OBJECTS) dialback.dll *.exp *.a

.PHONY: clean
