include ../platform-settings

CFLAGS:=$(CFLAGS) -I../jabberd


xdb_file_OBJECTS=xdb_file.o dllinit.o

single: static

all: xdb_file

xdb_file: $(xdb_file_OBJECTS)
	dllwrap --def ../cygwin/xdb_file.def --driver-name $(CC) -o xdb_file.dll $(xdb_file_OBJECTS) ../jabberd/jabberd.a $(LDFLAGS)

static: $(xdb_file_OBJECTS)

clean:
	rm -f $(xdb_file_OBJECTS) xdb_file.dll *.exp *.a

